name: jbr-linux-x64

on:
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 2 * *

jobs:
  update_aur:
    runs-on: ubuntu-latest
    name: Update AUR with the latest release
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update AUR
        id: aur
        uses: Kxuan/aur-release-action@f6683fd8e14c032be409b4c50bb5e7e55b166e56
        with:
          repo: RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
          author: kXuan <kxuanobj@gmail.com>